# Generated by Django 4.2.4 on 2023-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_less4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='lesson4/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
