# Generated by Django 4.1.4 on 2023-07-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_less4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='"advertisements"',
        ),
    ]
