# Generated by Django 4.1.4 on 2023-08-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_less4', '0007_remove_advertisement_user_id_advertisement_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
